CRITICAL - 2021-01-09 11:45:14 --> Unknown database 'tmans'
#0 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1845): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Model.php(445): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\intimes\app\Controllers\BaseController.php(94): CodeIgniter\Model->findAll()
#5 C:\xampp\htdocs\intimes\app\Controllers\A_login.php(32): App\Controllers\BaseController->common()
#6 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\A_login->index()
#7 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\A_login))
#8 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\intimes\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-01-09 11:45:14 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\intimes\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\intimes\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\A_login), true)
#2 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Debug\Exceptions.php(299): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Debug\Exceptions.php(172): CodeIgniter\Debug\Exceptions->render(Object(mysqli_sql_exception), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-09 11:45:52 --> Table 'chr_dashboards.a_menu' doesn't exist
#0 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1845): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Model.php(445): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\intimes\app\Controllers\BaseController.php(94): CodeIgniter\Model->findAll()
#6 C:\xampp\htdocs\intimes\app\Controllers\A_login.php(32): App\Controllers\BaseController->common()
#7 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\A_login->index()
#8 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\A_login))
#9 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\intimes\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2021-01-09 12:28:43 --> Unknown database 'intime'
#0 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1845): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Model.php(445): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\intimes\app\Controllers\BaseController.php(94): CodeIgniter\Model->findAll()
#5 C:\xampp\htdocs\intimes\app\Controllers\A_login.php(32): App\Controllers\BaseController->common()
#6 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\A_login->index()
#7 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\A_login))
#8 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\intimes\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-01-09 12:28:43 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\intimes\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\intimes\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\A_login), true)
#2 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Debug\Exceptions.php(299): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\intimes\vendor\codeigniter4\framework\system\Debug\Exceptions.php(172): CodeIgniter\Debug\Exceptions->render(Object(mysqli_sql_exception), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
